version: 0.2
phases:
  pre_build:
    commands:
      - . ${CODEBUILD_SRC_DIR}/build-scripts/pre_build.sh
  build:
    commands:
      - . ${CODEBUILD_SRC_DIR}/build-scripts/build.sh
artifacts:
  files:
    - ${BUILD_TEMPLATE_PATH}
    - ${PREBUILD_TEMPLATE_PATH}
  discard-paths: no