AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CloudFormation template to create s3 buckets.
Resources:
  usvpharmarawstorage:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: usv-pharma-raw
  usvpharmastgstorage:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: usv-pharma-stage
  usvpharmacurstorage:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: usv-pharma-curation
